global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-crud-starter'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /v1/metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
      